_prefs: 
  baselayer: matt.hb1g1mdo
  saveCenter: true
_properties: {}
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -157.78590202331543
  - 21.287694903185333
  - 14
description: Vector contours + Mapbox Streets labels for satellite map
format: "png8:m=h:c=128"
interactivity_layer: ''
layers: 
  - contour.line
  - tunnel
  - road
  - bridge
  - admin
  - country_label_line
  - country_label
  - marine_label
  - state_label
  - place_label
  - water_label
  - poi_label
  - road_label
  - waterway_label
  - contour.label
maxzoom: 22
minzoom: 0
mtime: 1396891680782
name: Satellite Contours + Labels
scale: 1
source: "mapbox:///mapbox.mapbox-terrain-v1,mapbox.mapbox-streets-v42-dev"
styles: 
  - contour.mss
  - labels.mss
template: ''
