_prefs: 
  baselayer: matt.hb1g1mdo
  saveCenter: true
_properties: {}
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -3.4277
  - 27.4888
  - 4
description: Vector contours + Mapbox Streets labels for satellite map
format: "png8:m=h:c=128"
interactivity_layer: ''
layers: 
  - mapbox_satellite_open
  - mapbox_satellite_plus
  - mapbox_satellite_full
  - mapbox_satellite_watermask
  - contour.line
  - landuse
  - waterway
  - water
  - aeroway
  - barrier_line
  - building
  - landuse_overlay
  - tunnel
  - road
  - bridge
  - admin
  - country_label_line
  - country_label
  - marine_label
  - state_label
  - place_label
  - water_label
  - poi_label
  - road_label
  - waterway_label
  - housenum_label
  - contour.label
maxzoom: 22
minzoom: 0
name: Satellite Contours + Labels
source: "mapbox:///mapbox.satellite,mapbox.mapbox-terrain-v2,mapbox.mapbox-streets-v5"
styles: 
  - contour.mss
  - labels.mss
  - satellite.mss
template: ''
