_prefs: 
  baselayer: matt.hb1g1mdo
  saveCenter: true
_properties: {}
attribution: "<a href='https://www.mapbox.com/about/maps/' target='_blank'>&copy; Mapbox &copy; OpenStreetMap</a> <a class='mapbox-improve-map' href='https://www.mapbox.com/map-feedback/' target='_blank'>Improve this map</a>"
bounds: 
  - -180
  - -85.0511
  - 180
  - 85.0511
center: 
  - -92.94433593749999
  - 36.50963615733049
  - 5
description: Vector contours + Mapbox Streets labels for satellite map
format: "png8:m=h:c=128"
interactivity_layer: ''
layers: null
maxzoom: 22
minzoom: 0
mtime: 1396545333730
name: Satellite Contours + Labels
scale: 1
source: "mapbox:///mapbox.mapbox-terrain-v1,mapbox.mapbox-streets-v4"
styles: 
  - contour.mss
  - labels.mss
template: ''
